/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();
    group.current.rotation.y = a;
  });
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/lucy/model.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null} scale={3.5}>
      <mesh
        geometry={nodes.lucy001.geometry}
        material={materials["Default OBJ.001"]}
        position={[0, -0.27, 0]}
      />
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/lucy/model.gltf"
);
